default: pdf

pdf:
	pandoc -t beamer  01_propositionsastypes.md -o 01_propositionsastypes.pdf
	pandoc -t beamer  02_logic.md -o 02_logic.pdf
	pandoc -t beamer  03_inductivetypes.md -o 03_inductivetypes.pdf
	pandoc -t beamer  04_tactics.md -o 04_tactics.pdf
	pandoc -t beamer  05_dependenttypes.md -o 05_dependenttypes.pdf
